### ISSUE TITLE
Front-End project build failed

### ISSUE THREAD

**Issue by abdulr-khan** [bkaminnski/NrgyInvoicR#16]
npm start failed to compile and throws this error in multiple places

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'

Tried few solutions npm rb, install sass and even removing module folder and re-installing but none of them work.

Would appreciate any help resolving this issue.

Thx
Rasheed Khan

**Comment by bkaminnski** [comment]
We've already fixed the problem, so here I will provide a short recap and will close the ticket.

At some point of time node-sass dependency required by Angular 7 became inaccessible. The fix was to update Angular version 7 to version 8 (commit be642683834ca5bbf512552780c0c2225fe7214a).
